### ISSUE TITLE
Wrong Content-Type when viewing picutres in Firefox

### ISSUE THREAD

**Issue by noqqe** [mvdan/pastecat#1]
Hi,

when you view pictures that were uploaded in firefox, content-type is wrong. See

![screen shot 2015-10-06 at 15 03 25](https://cloud.githubusercontent.com/assets/203902/10309172/5e8efcf0-6c3b-11e5-9f2e-59e001849565.png)

In Chrome and Safari everything works fine.

**Comment by mvdan** [comment]
This is on purpose - mimetypes are outside of the scope of the project. Any data is supported, but it is transferred as plaintext utf-8 as it is intended for text.

**Comment by mvdan** [comment]
I forgot to close this.
